### ISSUE TITLE
Suggestion: only add comment if there are no existing comments

### ISSUE THREAD

**Issue by p0358** [partoftheworlD/IDApy_FunctionStringAssociate#2]
Currently the plugin always nukes all function comments and then adds its own ones. I believe it'd be beneficial to add an option to skip over the function if it has any existing comments, to be able to run the plugin in a database that was already used with some comments added. And even if that behavior was optional, I think it still shouldn't nuke function comments before checking if the plugin will end up any comment itself (if there are >0 strings), as it might remove some auto-generated comment this way too.

The original plugin had something like that in a todo comment, but never ended up implementing it sadly
```cpp
// TODO: Could have option to just skip comment if one already exists?
```

**Comment by partoftheworlD** [comment]
I updated script, now it saves existing comments and adds them to found comments, try it and write me if it doesn't work as it should. Right now I don't have IDA to make tests. My concern is whether comments will be duplicated, the implementation I used shouldn't duplicate them, but without tests it's hard to say whether duplicate checking should be implemented.

538ac09
